### ISSUE TITLE
Only notify on spawn of living Chompy

### ISSUE THREAD

**Issue by CreativeTechGuy** [PJGJ210/chompy-hunter#4]
Currently the "Notify on spawn" setting notifies when a chompy appears, but this includes both alive and dead chompy birds. So as you are moving around, if there's dead chompy bodies near the edge of your client's load range, they'll be "spawning" and "despawning" as you move and that triggers notifications.

Can this only notify when a living chompy spawns?

**Comment by PJGJ210** [comment]
Pending https://github.com/runelite/plugin-hub/pull/7005
